"""empty message

Revision ID: b6f338f33cec
Revises: 8c95fce775f7
Create Date: 2023-05-26 19:44:54.633684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f338f33cec'
down_revision = '8c95fce775f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(
            sa.Column('image', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_column('image')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
