"""empty message

Revision ID: b901762c2ba3
Revises: b6f338f33cec
Create Date: 2023-05-26 19:49:26.928142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b901762c2ba3'
down_revision = 'b6f338f33cec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=100), nullable=True))
        batch_op.drop_column('picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###
