"""empty message

Revision ID: fa8e7416dfa6
Revises: 94a7e636ac1f
Create Date: 2023-05-26 13:31:07.486334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa8e7416dfa6'
down_revision = '94a7e636ac1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registers', schema=None) as batch_op:
        batch_op.alter_column('student',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('registers_subject_fkey', type_='foreignkey')
        batch_op.drop_column('subject')

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    with op.batch_alter_table('registers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('registers_subject_fkey', 'subjects', ['subject'], ['subject_id'])
        batch_op.alter_column('student',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
